-- CRM V3 - Otomasyonlar Tam Migration
-- Tüm otomasyonlar için gerekli veritabanı değişiklikleri
-- Next.js 15 + Supabase uyumlu

-- ============================================
-- 1. USER TABLOSU - AutoGoalTracker için
-- ============================================
ALTER TABLE "User" 
ADD COLUMN IF NOT EXISTS "monthlyGoal" DECIMAL(15, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS "preferredCurrency" VARCHAR(10) DEFAULT 'TRY',
ADD COLUMN IF NOT EXISTS "lastSearchHistory" JSONB DEFAULT '[]'::jsonb;

-- Index
CREATE INDEX IF NOT EXISTS idx_user_monthly_goal ON "User"("monthlyGoal");

-- ============================================
-- 2. QUOTE TABLOSU - AutoQuoteExpiry için
-- ============================================
ALTER TABLE "Quote" 
ADD COLUMN IF NOT EXISTS "expiryDate" DATE,
ADD COLUMN IF NOT EXISTS "priorityScore" DECIMAL(10, 2) DEFAULT 0;

-- Index'ler
CREATE INDEX IF NOT EXISTS idx_quote_expiry_date ON "Quote"("expiryDate");
CREATE INDEX IF NOT EXISTS idx_quote_priority_score ON "Quote"("priorityScore");
CREATE INDEX IF NOT EXISTS idx_quote_status_expiry ON "Quote"("status", "expiryDate");

-- ============================================
-- 3. DEAL TABLOSU - Auto-Priority Lead Sorting için
-- ============================================
ALTER TABLE "Deal" 
ADD COLUMN IF NOT EXISTS "priorityScore" DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS "isPriority" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "quoteCreatedAt" TIMESTAMP WITH TIME ZONE;

-- Index'ler
CREATE INDEX IF NOT EXISTS idx_deal_priority_score ON "Deal"("priorityScore");
CREATE INDEX IF NOT EXISTS idx_deal_is_priority ON "Deal"("isPriority");
CREATE INDEX IF NOT EXISTS idx_deal_quote_created ON "Deal"("quoteCreatedAt");

-- ============================================
-- 4. CUSTOMER TABLOSU - Churn Prediction için
-- ============================================
ALTER TABLE "Customer" 
ADD COLUMN IF NOT EXISTS "churnScore" DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS "riskLevel" VARCHAR(20) DEFAULT 'LOW',
ADD COLUMN IF NOT EXISTS "lastInteractionDate" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "birthday" DATE,
ADD COLUMN IF NOT EXISTS "satisfactionScore" DECIMAL(5, 2) DEFAULT 0;

-- Index'ler
CREATE INDEX IF NOT EXISTS idx_customer_churn_score ON "Customer"("churnScore");
CREATE INDEX IF NOT EXISTS idx_customer_risk_level ON "Customer"("riskLevel");
CREATE INDEX IF NOT EXISTS idx_customer_last_interaction ON "Customer"("lastInteractionDate");
CREATE INDEX IF NOT EXISTS idx_customer_birthday ON "Customer"("birthday");

-- CHECK constraint - riskLevel
ALTER TABLE "Customer"
DROP CONSTRAINT IF EXISTS check_customer_risk_level;

ALTER TABLE "Customer"
ADD CONSTRAINT check_customer_risk_level 
CHECK ("riskLevel" IN ('LOW', 'MEDIUM', 'HIGH'));

-- ============================================
-- 5. INVOICE TABLOSU - SmartFileNaming için
-- ============================================
ALTER TABLE "Invoice" 
ADD COLUMN IF NOT EXISTS "invoiceNumber" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "autoGeneratedFileName" VARCHAR(255);

-- Index
CREATE INDEX IF NOT EXISTS idx_invoice_number ON "Invoice"("invoiceNumber");

-- ============================================
-- 6. TASK TABLOSU - Late Task Escalation için
-- ============================================
ALTER TABLE "Task" 
ADD COLUMN IF NOT EXISTS "escalated" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "escalatedAt" TIMESTAMP WITH TIME ZONE;

-- Index - dueDate kolonu varsa index oluştur (schema-extension'da var ama migration çalıştırılmamış olabilir)
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'Task' AND column_name = 'dueDate'
  ) THEN
    CREATE INDEX IF NOT EXISTS idx_task_due_date ON "Task"("dueDate");
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_task_escalated ON "Task"("escalated");

-- ============================================
-- 7. MEETING TABLOSU - AutoMeetingSummary için
-- ============================================
-- Meeting tablosu varsa kolon ekle
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'Meeting') THEN
    ALTER TABLE "Meeting" 
    ADD COLUMN IF NOT EXISTS "autoSummary" TEXT,
    ADD COLUMN IF NOT EXISTS "summaryGenerated" BOOLEAN DEFAULT false;
    
    CREATE INDEX IF NOT EXISTS idx_meeting_summary_generated ON "Meeting"("summaryGenerated");
  END IF;
END $$;

-- ============================================
-- 8. QUOTE STATUS - EXPIRED ekle
-- ============================================
-- Quote tablosunda status kolonu için EXPIRED değerini destekle
-- (Zaten VARCHAR olduğu için constraint gerekmez, sadece kontrol)

-- ============================================
-- 9. TRIGGER: AutoQuoteExpiry - Otomatik süre dolumu
-- ============================================
CREATE OR REPLACE FUNCTION auto_expire_quotes()
RETURNS TRIGGER AS $$
BEGIN
  -- 30 günden uzun süredir SENT olan teklifleri EXPIRED yap
  UPDATE "Quote"
  SET status = 'EXPIRED',
      "updatedAt" = NOW()
  WHERE status = 'SENT'
    AND "createdAt" < NOW() - INTERVAL '30 days'
    AND "companyId" = NEW."companyId";
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_auto_expire_quotes ON "Quote";
CREATE TRIGGER trigger_auto_expire_quotes
  AFTER INSERT OR UPDATE ON "Quote"
  FOR EACH ROW
  EXECUTE FUNCTION auto_expire_quotes();

-- ============================================
-- 10. TRIGGER: Update Customer Last Interaction
-- ============================================
CREATE OR REPLACE FUNCTION update_customer_last_interaction()
RETURNS TRIGGER AS $$
DECLARE
  customer_id_from_deal UUID;
BEGIN
  -- Quote oluşturulduğunda müşterinin lastInteractionDate'ini güncelle
  -- Quote tablosunda customerId yok, Deal üzerinden Customer'a ulaşılır
  IF NEW."dealId" IS NOT NULL THEN
    -- Deal'den customerId'yi al
    SELECT "customerId" INTO customer_id_from_deal
    FROM "Deal"
    WHERE id = NEW."dealId"
      AND "companyId" = NEW."companyId";
    
    IF customer_id_from_deal IS NOT NULL THEN
      UPDATE "Customer"
      SET "lastInteractionDate" = NOW(),
          "updatedAt" = NOW()
      WHERE id = customer_id_from_deal
        AND "companyId" = NEW."companyId";
    END IF;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_customer_last_interaction_quote ON "Quote";
CREATE TRIGGER trigger_update_customer_last_interaction_quote
  AFTER INSERT ON "Quote"
  FOR EACH ROW
  EXECUTE FUNCTION update_customer_last_interaction();

-- Invoice için de aynı trigger
DROP TRIGGER IF EXISTS trigger_update_customer_last_interaction_invoice ON "Invoice";
CREATE TRIGGER trigger_update_customer_last_interaction_invoice
  AFTER INSERT ON "Invoice"
  FOR EACH ROW
  EXECUTE FUNCTION update_customer_last_interaction();

-- ============================================
-- 11. TRIGGER: Update Deal Quote Created At
-- ============================================
CREATE OR REPLACE FUNCTION update_deal_quote_created()
RETURNS TRIGGER AS $$
BEGIN
  -- Quote oluşturulduğunda deal'in quoteCreatedAt'ini güncelle
  IF NEW."dealId" IS NOT NULL THEN
    UPDATE "Deal"
    SET "quoteCreatedAt" = NOW(),
        "updatedAt" = NOW()
    WHERE id = NEW."dealId"
      AND "companyId" = NEW."companyId";
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_deal_quote_created ON "Quote";
CREATE TRIGGER trigger_update_deal_quote_created
  AFTER INSERT ON "Quote"
  FOR EACH ROW
  EXECUTE FUNCTION update_deal_quote_created();

-- ============================================
-- 12. FUNCTION: Calculate Churn Score
-- ============================================
CREATE OR REPLACE FUNCTION calculate_churn_score(customer_id UUID, company_id UUID)
RETURNS DECIMAL(10, 2) AS $$
DECLARE
  inactive_days INTEGER;
  rejected_quotes INTEGER;
  churn_score DECIMAL(10, 2);
BEGIN
  -- İnaktif gün sayısını hesapla
  SELECT COALESCE(EXTRACT(DAY FROM (NOW() - "lastInteractionDate")), 0)::INTEGER
  INTO inactive_days
  FROM "Customer"
  WHERE id = customer_id AND "companyId" = company_id;
  
  -- Reddedilen teklif sayısını bul (Deal üzerinden Customer'a ulaşılır)
  SELECT COUNT(*)
  INTO rejected_quotes
  FROM "Quote" q
  INNER JOIN "Deal" d ON q."dealId" = d.id
  WHERE d."customerId" = customer_id
    AND q."companyId" = company_id
    AND q.status = 'DECLINED';
  
  -- Churn skoru hesapla: (inaktif_günler * 0.5) + (reddedilen_teklifler * 1.5)
  churn_score := (inactive_days * 0.5) + (rejected_quotes * 1.5);
  
  RETURN churn_score;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 13. FUNCTION: Calculate Priority Score
-- ============================================
CREATE OR REPLACE FUNCTION calculate_priority_score(deal_id UUID, company_id UUID)
RETURNS DECIMAL(10, 2) AS $$
DECLARE
  deal_value DECIMAL(15, 2);
  customer_score DECIMAL(10, 2);
  win_probability INTEGER;
  days_since_creation INTEGER;
  priority_score DECIMAL(10, 2);
BEGIN
  -- Deal bilgilerini al
  SELECT value, "winProbability", EXTRACT(DAY FROM (NOW() - "createdAt"))::INTEGER
  INTO deal_value, win_probability, days_since_creation
  FROM "Deal"
  WHERE id = deal_id AND "companyId" = company_id;
  
  -- Müşteri skoru (basit: müşterinin toplam ciro / 10000)
  SELECT COALESCE(SUM(total) / 10000, 1)
  INTO customer_score
  FROM "Invoice"
  WHERE "customerId" = (SELECT "customerId" FROM "Deal" WHERE id = deal_id)
    AND "companyId" = company_id
    AND status = 'PAID';
  
  customer_score := LEAST(10, GREATEST(1, customer_score));
  
  -- Olasılık
  IF win_probability IS NULL THEN
    win_probability := 50;
  END IF;
  
  -- Gün sayısı (minimum 1)
  days_since_creation := GREATEST(1, days_since_creation);
  
  -- Puan hesapla: (teklif_tutarı × müşteri_skoru × olasılık) / gün_sayısı
  priority_score := (deal_value * customer_score * (win_probability::DECIMAL / 100)) / days_since_creation;
  
  RETURN priority_score;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 14. VIEW: Risky Customers View
-- ============================================
CREATE OR REPLACE VIEW "RiskyCustomers" AS
SELECT 
  c.id,
  c.name,
  c.email,
  c."churnScore",
  c."riskLevel",
  c."lastInteractionDate",
  EXTRACT(DAY FROM (NOW() - c."lastInteractionDate"))::INTEGER AS "daysSinceInteraction",
  (SELECT COUNT(*) 
   FROM "Quote" q
   INNER JOIN "Deal" d ON q."dealId" = d.id
   WHERE d."customerId" = c.id AND q.status = 'DECLINED') AS "rejectedQuotes"
FROM "Customer" c
WHERE c."churnScore" > 10
  AND c.status = 'ACTIVE'
ORDER BY c."churnScore" DESC;

-- ============================================
-- 15. VIEW: Priority Deals View
-- ============================================
CREATE OR REPLACE VIEW "PriorityDeals" AS
SELECT 
  d.id,
  d.title,
  d.value,
  d.stage,
  d."priorityScore",
  d."isPriority",
  d."createdAt",
  d."quoteCreatedAt",
  EXTRACT(DAY FROM (NOW() - d."createdAt"))::INTEGER AS "daysSinceCreation"
FROM "Deal" d
WHERE d."isPriority" = true
  AND d.status = 'OPEN'
ORDER BY d."priorityScore" DESC;

-- ============================================
-- 16. INDEX'LER - Performans için
-- ============================================
CREATE INDEX IF NOT EXISTS idx_quote_status_created ON "Quote"("status", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_status_created ON "Invoice"("status", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS idx_customer_status_updated ON "Customer"("status", "updatedAt" DESC);
CREATE INDEX IF NOT EXISTS idx_deal_status_created ON "Deal"("status", "createdAt" DESC);
-- Index - dueDate kolonu varsa index oluştur
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'Task' AND column_name = 'dueDate'
  ) THEN
    CREATE INDEX IF NOT EXISTS idx_task_due_date_status ON "Task"("dueDate", "status");
  END IF;
END $$;

-- ============================================
-- 17. COMMENT'LER - Dokümantasyon için
-- ============================================
COMMENT ON COLUMN "User"."monthlyGoal" IS 'Aylık satış hedefi (AutoGoalTracker için)';
COMMENT ON COLUMN "User"."preferredCurrency" IS 'Tercih edilen para birimi (AutoCurrencyDisplay için)';
COMMENT ON COLUMN "Quote"."expiryDate" IS 'Teklif geçerlilik tarihi (AutoQuoteExpiry için)';
COMMENT ON COLUMN "Quote"."priorityScore" IS 'Teklif öncelik puanı';
COMMENT ON COLUMN "Deal"."priorityScore" IS 'Fırsat öncelik puanı (Auto-Priority Lead Sorting için)';
COMMENT ON COLUMN "Deal"."isPriority" IS 'Öncelikli fırsat mı?';
COMMENT ON COLUMN "Customer"."churnScore" IS 'Kayıp müşteri tahmin skoru (Churn Prediction için)';
COMMENT ON COLUMN "Customer"."riskLevel" IS 'Risk seviyesi: LOW, MEDIUM, HIGH';
COMMENT ON COLUMN "Customer"."satisfactionScore" IS 'Müşteri memnuniyet skoru (0-100)';

-- ============================================
-- MIGRATION TAMAMLANDI
-- ============================================

